### ISSUE TITLE
Asking for information about httpd in respositories

### ISSUE THREAD

**Issue by abcdefg-png** [didi-zhiyuan/vuln#1]
What's the version of Tenda httpd file? Is that Tenda W15Ev1.0?
![image](https://github.com/didi-zhiyuan/vuln/assets/74417586/c71ec789-c55b-4731-9967-b5fa46a8b265)

**Comment by Zhi0Yuan** [comment]
Yes This httpd is the httpd previously extracted from W15Ev1.0 firmware 
The specific version is V15.11.0.14

**Comment by abcdefg-png** [comment]
> Yes This httpd is the httpd previously extracted from W15Ev1.0 firmware The specific version is V15.11.0.14

Sorry bro, you may need to check the "httpd" in this respositories, I can't find the function mentioned in your respositories, which can comfirm that the httpd makes a mistake.
Additionally, the name of Tenda router in the CVE description also has a mistake, which misspell W15E to V15E. I also made mistake in my CVEs, you can update it in cveform!😊

**Comment by Zhi0Yuan** [comment]
Sorry for my question, this httpd is indeed not the httpd in W15EV1. If you need it, you can download it directly from the official website.

**Comment by 0-fool** [comment]
I downloaded W15E from the Tenda official website. After unpacking, when using QEMU for emulation, I encountered the following error if no parameters were added.

<img width="736" height="1138" alt="Image" src="https://github.com/user-attachments/assets/3af6c826-d361-41eb-854a-bf134c2f287e" />

After adding parameters, it can start normally, but I can only access the initial webpage.

<img width="831" height="1406" alt="Image" src="https://github.com/user-attachments/assets/9230b334-3b5f-4995-a92b-beba2a0b51a9" />

<img width="2134" height="746" alt="Image" src="https://github.com/user-attachments/assets/326fadbc-8734-41c3-8e37-c3f54ecba3ce" />

Could you please share your emulation process for my reference?

**Comment by Zhi0Yuan** [comment]
> I downloaded W15E from the Tenda official website. After unpacking, when using QEMU for emulation, I encountered the following error if no parameters were added.
> 
> <img alt="Image" width="736" height="1138" src="https://private-user-images.githubusercontent.com/213414578/499365906-3af6c826-d361-41eb-854a-bf134c2f287e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwMjYwODIsIm5iZiI6MTc2MDAyNTc4MiwicGF0aCI6Ii8yMTM0MTQ1NzgvNDk5MzY1OTA2LTNhZjZjODI2LWQzNjEtNDFlYi04NTRhLWJmMTM0YzJmMjg3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwOVQxNjAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmFkZmJjYTY0M2YzMjZlZjUzZDFmNzBhZWRiZGFkMjA1YzJmNjQ5Njc4MDBmZDFkNGY1MTBhM2I2MmU5NGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IhGf2nzaSHwwQzrQGavtHaWvr-cdKH5FW2FxQb4WldI">
> After adding parameters, it can start normally, but I can only access the initial webpage.
> 
> <img alt="Image" width="831" height="1406" src="https://private-user-images.githubusercontent.com/213414578/499366471-9230b334-3b5f-4995-a92b-beba2a0b51a9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwMjYwODIsIm5iZiI6MTc2MDAyNTc4MiwicGF0aCI6Ii8yMTM0MTQ1NzgvNDk5MzY2NDcxLTkyMzBiMzM0LTNiNWYtNDk5NS1hOTJiLWJlYmEyYTBiNTFhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwOVQxNjAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTNlZWU5NGYzNjViZjNmMGRhYTdiYjM4OTc5ZDkzMzJlYWZlNDU3ZGZmZmQ5MWRmM2JhNmQ2NGMzMmQyNDIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MErmIJ2L6mF79duz-OJ-xqTT-8EJ4Hb9LJsnF_ihlxk"> <img alt="Image" width="2000" height="746" src="https://private-user-images.githubusercontent.com/213414578/499366573-326fadbc-8734-41c3-8e37-c3f54ecba3ce.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwMjYwODIsIm5iZiI6MTc2MDAyNTc4MiwicGF0aCI6Ii8yMTM0MTQ1NzgvNDk5MzY2NTczLTMyNmZhZGJjLTg3MzQtNDFjMy04ZTM3LWMzZjU0ZWNiYTNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwOVQxNjAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzg1ZTM1ZjFkMDZjNDE1NTQ5ZDBjYjJhY2YzZWMwMTYzOGMwZTA4NjRkZWE1NjZiZDZmNmNkZDI4MDc2Njg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6ZQHhSXiSGeJnTSe1L9O5M55D5DnyTLHkh6wfdIdC10">
> Could you please share your emulation process for my reference?

时间有点久了，我没记错的话当时应该是patch过httpd服务才正常运行，你可以对比一下md5值看看是否一样

**Comment by 0-fool** [comment]
是和vuln中Tenda下面的httpd服务比较吗？我看了一下这个httpd好像不是W15E的httpd

**Comment by Zhi0Yuan** [comment]
> 是和vuln中Tenda下面的httpd服务比较吗？我看了一下这个httpd好像不是W15E的httpd

好吧，那我确实不记得这个httpd是哪个设备的了，但是我能确定的是我这个Tenda目录下的httpd服务是修改过的跳过了某些启动判断。

**Comment by 0-fool** [comment]
okok,感谢
